### ISSUE TITLE
Poly Gates and Trigger don't work in Rack V1

### ISSUE THREAD

**Issue by brickzone** [SmallTownSound/STS#10]
So is the subject. By the way poly 1voct works awesome, but gates don't work at all...

**Comment by brickzone** [comment]
I forgot to mention - I'm on Windows

**Comment by SmallTownSound** [comment]
Sorry for no documentation yet....   the lighted switches on the end of the rows are channel on/off.  They have to be lit for the gates and trigger to send output.
They will be labelled and initialized to on in the next release comigi n a few days

**Comment by SmallTownSound** [comment]
The port is for CV control of the on/off
