### ISSUE TITLE
WaveFolder GUI wrong

### ISSUE THREAD

**Issue by Petervos2018** [SmallTownSound/STS#17]
I don't think you want this to look like this do you ?

![WaveFoldGUI](https://user-images.githubusercontent.com/46076474/63652396-1a16cb00-c760-11e9-9c28-0303cba016df.jpg)
Either the svg or the placing of the elements is wrong/off.

Windows 7 module version 1.0.4.

Greetings Peter.

**Comment by SmallTownSound** [comment]
CRAP..  I missed reverting the CPP file to the earlier one, it was in the middle of updating, adding some cv inputs..  It works fine, just looks funky. 
The 2 bottom CV ins were added, hadn't got around to updating the SVG yet..  The 2 CVs are not working. but not as nicely as I would want, they should follow the same taper as the 2 pots (knobs), but wasn't done with them yet.   will do update asap..
Don
