### ISSUE TITLE
Rack v1: plugin.json needs updates

### ISSUE THREAD

**Issue by cschol** [SmallTownSound/STS#7]
The following updates are required for the `plugin.json`:

- `license`: Use an official designation from https://spdx.org/licenses/ for the license field
- `sourceUrl`: Set to GitHub source URL
- `pluginUrl`: Set to URL to GitHub `README.md` 
- `manualUrl`: Set to URL to GitHub `README.md`

**Comment by cschol** [comment]
Sorry, I should have been more specific on the license. It should be the **SPDX identifier** (so it can be parsed):

```
GPL-3.0-only
```

**Comment by cschol** [comment]
You committed a file with a merge conflict (plugin.json). Please resolve. Thanks!

**Comment by SmallTownSound** [comment]
I pushed the updated json file..  what was I supposed to do?

**Comment by cschol** [comment]
Look at the file: https://github.com/SmallTownSound/STS/blob/V1/plugin.json

It has merge conflicts that need to be resolved and the file needs to be re-committed.

**Comment by SmallTownSound** [comment]
STS V1.0.2 is ready for library

https://github.com/SmallTownSound/STS/

commit e634dffdff077e669c3d475defef6ec0a54a2247

**Comment by cschol** [comment]
Please post this in the library repo issue. We will reopen it. Thanks!
